// js/data.js — single source of truth

// ── Chomsky type definitions ─────────────────────────────────────────────────
const CHOMSKY_DATA = {
  re: {
    type:'re', badge:'Type 0', title:'Recursively Enumerable',
    grammar:'α → β   where α,β ∈ (V∪T)*, |α| ≥ 1',
    def:'The most powerful class. A Turing Machine can accept these languages — but may loop forever on strings NOT in the language. There is no guarantee of halting on rejection. These languages are "semi-decidable."',
    automaton:'Turing Machine (TM)',
    examples:['Halting Problem — most famous undecidable language','Post Correspondence Problem','Any language reducible to TM acceptance','Diagonalization language — not even RE'],
    diagram:'tm',
    sim_explanation: 'A Turing Machine (TM) has an infinite tape and a read/write head. In this simulation, watch the head move left and right across the tape. Unlike simpler automata, a TM can write new symbols (like turning a, b into X, Y) and move in both directions freely. This unbounded memory allows it to compute anything that is computable.'
  },
  cs: {
    type:'cs', badge:'Type 1', title:'Context-Sensitive',
    grammar:'αAβ → αγβ   (γ ≠ ε, productions cannot shrink)',
    def:'Recognized by a Linear Bounded Automaton — a Turing Machine whose tape is bounded to the length of the input. Productions can only grow or stay the same length. Membership is decidable but PSPACE-hard.',
    automaton:'Linear Bounded Automaton (LBA)',
    examples:['aⁿbⁿcⁿ — equal counts of three symbols','aⁿbⁿcⁿdⁿ — equal counts of four symbols','aⁿbⁿcⁿdⁿeⁿ — equal counts of five symbols','ww — copy language (w concatenated with itself)'],
    diagram:'lba',
    sim_explanation: 'A Linear Bounded Automaton (LBA) acts just like a Turing Machine, but its tape is restricted strictly to the length of the input string bounded by endmarkers ⊢ and ⊣. Watch the head sweep back and forth to mark off equal parts of the structure! It cannot use extra tape space.'
  },
  cf: {
    type:'cf', badge:'Type 2', title:'Context-Free',
    grammar:'A → γ   where A ∈ V (single non-terminal on left)',
    def:'Generated by context-free grammars and recognized by Pushdown Automata (PDA). A single stack provides memory for matching patterns. Widely used for programming language syntax — parsers use CFGs.',
    automaton:'Pushdown Automaton (PDA)',
    examples:['aⁿbⁿ — equal a\'s and b\'s (n ≥ 0)','Balanced parentheses: (), (()), ((()))','Palindromes over {a,b}','Arithmetic expressions: (a+b)*c'],
    diagram:'pda',
    sim_explanation: 'A Pushdown Automaton (PDA) relies on a Stack (LIFO). Watch the simulation as it pushes an "A" onto the stack for every first part of the pattern, and then pops an "A" off for the second part. If the stack resolves exactly to the initial marker (Z₀) when the input is done, the pattern is balanced and accepted!'
  },
  reg: {
    type:'reg', badge:'Type 3', title:'Regular Languages',
    grammar:'A → aB  or  A → a   (right-linear only)',
    def:'The simplest class. Recognized by Finite Automata (DFA/NFA) and described by Regular Expressions. A DFA has no memory beyond its current state — it cannot count or match nested patterns. Extremely fast to decide.',
    automaton:'Deterministic Finite Automaton (DFA)',
    examples:['a* — zero or more a\'s','a*b* — some a\'s followed by some b\'s','Strings ending in "ab"','Lexical tokens: identifiers, integers, keywords'],
    diagram:'dfa',
    sim_explanation: 'A Deterministic Finite Automaton (DFA) has no stack or tape memory—it only remembers its current state. Watch the highlight move strictly from state to state as each character is consumed. If it lands on an accepting state (double circle) at the very end of the string, the string is accepted. No counting is possible!'
  }
};

// ── Simulate: classification rules ──────────────────────────────────────────
// Each rule: patterns[], type, and steps with optional diagram key
const SIM_RULES = [
  {
    // Regular languages (general / a*b* patterns)
    patterns:['a*','b*','c*','a+','b+','c+','a*b*','0*1*','(ab)*','(abc)*','(ab)+','(a|b)*','(a|b|c)*','(a+b+c)*','ab*','a*b','a*ba*','a*b*c*','a*c*','b*c*','a+b*','a*b+','a+b+','a+c*','b+c*','abc*','a+b*c*','ab','abc','(0|1)*'],
    type:'reg',
    samples: ['ε', 'a', 'b', 'aa', 'ab', 'bb', 'aaa', 'aab', 'abb', 'bbb'],

    steps:[
      { check:'Is it Regular (Type 3)?', result:'pass',
        detail:'This language can be described by a regular expression and recognized by a DFA. The automaton needs no memory — only a finite set of states tracks everything needed.',
        rule:'✓ Finite Automaton suffices — no counting or stack required',
        diagram:'dfa' },
      { check:'Is it Context-Free (Type 2)?', result:'pass',
        detail:'Every regular language is also context-free (Regular ⊂ CFL). But this is redundant — we already have a tighter classification.',
        rule:'✓ Reg ⊂ CF — passes, but Type 3 is the tightest class' },
      { check:'Is it Context-Sensitive (Type 1)?', result:'pass',
        detail:'Similarly, all CFLs are context-sensitive. Passes here too, but Type 3 is still the tightest.',
        rule:'✓ CF ⊂ CS — passes, but not the tightest class' },
      { check:'Is it Recursively Enumerable (Type 0)?', result:'pass',
        detail:'A TM can trivially simulate any DFA. Passes everywhere — but the classification is Type 3.',
        rule:'✓ CS ⊂ RE — passes at every level, tightest class = Type 3' }
    ]
  },
  {
    // Regular languages (ends with specific pattern)
    patterns:['strings ending in ab','strings ending in 0','strings ending in 1'],
    type:'reg',
    samples: ['ab', 'aab', 'bab', 'aaab', 'abab', 'bbab', 'baaab', 'abbab'],

    steps:[
      { check:'Is it Regular (Type 3)?', result:'pass',
        detail:'Recognizing a suffix only requires a DFA to track the last few characters read. Finite states are perfectly sufficient.',
        rule:'✓ Finite Automaton suffices — finite suffix tracking',
        diagram:'dfa' },
      { check:'Is it Context-Free (Type 2)?', result:'pass',
        detail:'Every regular language is also context-free (Regular ⊂ CFL). But this is redundant — we already have a tighter classification.',
        rule:'✓ Reg ⊂ CF — passes, but Type 3 is the tightest class' },
      { check:'Is it Context-Sensitive (Type 1)?', result:'pass',
        detail:'Similarly, all CFLs are context-sensitive. Passes here too, but Type 3 is still the tightest.',
        rule:'✓ CF ⊂ CS — passes, but not the tightest class' },
      { check:'Is it Recursively Enumerable (Type 0)?', result:'pass',
        detail:'A TM can trivially simulate any DFA. Passes everywhere.',
        rule:'✓ CS ⊂ RE — passes at every level, tightest class = Type 3' }
    ]
  },
  {
    // Context-free languages: aⁿbⁿ
    patterns:['aⁿbⁿ','anbn','a^n b^n','aⁿbⁿ (n≥0)','aⁿbⁿ (n>=0)','a^nb^n'],
    type:'cf',
    samples: ['ε', 'ab', 'aabb', 'aaabbb', 'aaaabbbb', 'aaaaabbbbb'],

    steps:[
      { check:'Is it Regular (Type 3)?', result:'fail',
        detail:'This language requires counting and matching equal quantities. A DFA has no memory — it cannot track how many a\'s it saw. The Pumping Lemma for Regular Languages is violated: pumping any long string breaks the balance.',
        rule:'✗ Cannot be described by any DFA or Regex — counting is required',
        diagram:'dfa' },
      { check:'Is it Context-Free (Type 2)?', result:'pass',
        detail:'A Pushdown Automaton can handle this perfectly: push each "a" onto the stack, then pop one for each "b". When the stack is empty and input is finished — accept. The stack provides exactly the memory needed.',
        rule:'✓ PDA: push a\'s onto stack, pop for each b — stack memory is sufficient',
        diagram:'pda' },
      { check:'Is it Context-Sensitive (Type 1)?', result:'pass',
        detail:'All context-free languages are also context-sensitive. A Linear Bounded Automaton can trivially simulate a PDA.',
        rule:'✓ CFL ⊂ CSL — passes, but Type 2 is the tightest class' },
      { check:'Is it Recursively Enumerable (Type 0)?', result:'pass',
        detail:'A Turing Machine can simulate a PDA. Passes at this level too, but classification stays at Type 2.',
        rule:'✓ CSL ⊂ RE — passes everywhere, tightest class = Type 2' }
    ]
  },
  {
    // Context-free languages: Palindromes
    patterns:['palindrome','palindromes','palindrome over {a,b}'],
    type:'cf',
    samples: ['ε', 'a', 'b', 'aa', 'bb', 'aba', 'bab', 'aaaa', 'abba', 'baab'],

    steps:[
      { check:'Is it Regular (Type 3)?', result:'fail',
        detail:'Requires matching elements around a midpoint. A DFA has no unbound memory to remember the first half of a string to check against the second half.',
        rule:'✗ Cannot be evaluated by any DFA — tracking string halves is required',
        diagram:'dfa' },
      { check:'Is it Context-Free (Type 2)?', result:'pass',
        detail:'A Non-deterministic Pushdown Automaton handles this: push the first half onto the stack, non-deterministically guess the middle, then pop while matching the second half.',
        rule:'✓ NPDA: non-deterministically guess the middle, use stack to reverse match',
        diagram:'pda' },
      { check:'Is it Context-Sensitive (Type 1)?', result:'pass',
        detail:'All context-free languages are also context-sensitive. A Linear Bounded Automaton can easily verify palindromes by moving back and forth.',
        rule:'✓ CFL ⊂ CSL — passes, but Type 2 is the tightest class' },
      { check:'Is it Recursively Enumerable (Type 0)?', result:'pass',
        detail:'A Turing Machine can simulate an LBA or a PDA. Passes at this level too.',
        rule:'✓ CSL ⊂ RE — passes everywhere, tightest class = Type 2' }
    ]
  },
  {
    // Context-free languages: Balanced parentheses
    patterns:['balanced parentheses','balanced brackets','matched brackets','balanced braces','well-formed parentheses','well formed parentheses','dyck language','dyck word','dyck'],
    type:'cf',
    samples: ['ε', '()', '(())', '()()', '((()))', '(()())', '()()()'],

    steps:[
      { check:'Is it Regular (Type 3)?', result:'fail',
        detail:'Requires tracking arbitrary levels of nesting. A DFA\'s finite memory means it cannot keep an unbounded counter of nesting depth.',
        rule:'✗ Cannot be described by any DFA or Regex — nesting depth counting required',
        diagram:'dfa' },
      { check:'Is it Context-Free (Type 2)?', result:'pass',
        detail:'A Deterministic Pushdown Automaton handles this properly: push onto the stack when you see open brackets, pop when you see close brackets.',
        rule:'✓ DPDA: push on open brackets, pop on close brackets',
        diagram:'pda' },
      { check:'Is it Context-Sensitive (Type 1)?', result:'pass',
        detail:'All context-free languages are context-sensitive. A Linear Bounded Automaton can match brackets back-and-forth.',
        rule:'✓ CFL ⊂ CSL — passes, but Type 2 is the tightest class' },
      { check:'Is it Recursively Enumerable (Type 0)?', result:'pass',
        detail:'A Turing Machine can simulate an LBA or a PDA. Passes at this level too.',
        rule:'✓ CSL ⊂ RE — passes everywhere, tightest class = Type 2' }
    ]
  },
  {
    // Context-sensitive — aⁿbⁿcⁿ (3 symbols)
    patterns:['aⁿbⁿcⁿ','anbncn','a^n b^n c^n','aⁿbⁿcⁿ (n≥1)','a^nb^nc^n'],
    type:'cs',
    samples: ['abc', 'aabbcc', 'aaabbbccc', 'aaaabbbbcccc', 'aaaabbbbbcccccc'],

    steps:[
      { check:'Is it Regular (Type 3)?', result:'fail',
        detail:'Requires matching three separate equal quantities simultaneously. Far beyond any finite automaton — a DFA has no memory at all.',
        rule:'✗ No finite automaton can track multiple equal counts',
        diagram:'dfa' },
      { check:'Is it Context-Free (Type 2)?', result:'fail',
        detail:'A PDA has only ONE stack. To verify aⁿbⁿcⁿ, you must match n a\'s, n b\'s, AND n c\'s — but after using the stack to match a\'s and b\'s, there\'s no memory left to also match c\'s. The CFL Pumping Lemma is violated.',
        rule:'✗ Single stack insufficient — CFL Pumping Lemma is violated',
        diagram:'pda' },
      { check:'Is it Context-Sensitive (Type 1)?', result:'pass',
        detail:'A Linear Bounded Automaton solves this elegantly: scan left-to-right, mark off one a, one b, one c at a time in repeated passes. The tape bounded to input length is exactly enough memory.',
        rule:'✓ LBA marks off one (a,b,c) triple per sweep — bounded tape suffices',
        diagram:'lba' },
      { check:'Is it Recursively Enumerable (Type 0)?', result:'pass',
        detail:'A Turing Machine can trivially simulate an LBA. Passes here too, but Type 1 is the tightest classification.',
        rule:'✓ CSL ⊂ RE — passes, but tightest class = Type 1' }
    ]
  },
  {
    // Context-sensitive — ww (Copy Language)
    patterns:['ww','copy language','copy of w'],
    type:'cs',
    samples: ['ε', 'aa', 'bb', 'abab', 'baba', 'aabbaa', 'aaaa', 'bbbb', 'abbaabba'],

    steps:[
      { check:'Is it Regular (Type 3)?', result:'fail',
        detail:'Requires matching an arbitrarily long string exactly. A DFA lacks the unbounded memory to store the first half in order to compare it with the second half.',
        rule:'✗ No finite automaton can store an arbitrary string for exact matching',
        diagram:'dfa' },
      { check:'Is it Context-Free (Type 2)?', result:'fail',
        detail:'A PDA operates on a LIFO stack (Last-In, First-Out), making it excellent for reversing strings (palindromes). But for the copy language (ww), we need a FIFO queue layout to match the front of the first string to the front of the second string. A single stack cannot repeatedly cycle elements. Pumping lemma violated.',
        rule:'✗ Single stack insufficient — LIFO memory cannot handle exact non-reversed repetition',
        diagram:'pda' },
      { check:'Is it Context-Sensitive (Type 1)?', result:'pass',
        detail:'A Linear Bounded Automaton solves this. It sweeps back and forth finding the middle, and then marks symbols one by one from the first half to ensure they match the corresponding symbol in the second half.',
        rule:'✓ LBA sweeps back and forth to match halves — bounded tape suffices',
        diagram:'lba' },
      { check:'Is it Recursively Enumerable (Type 0)?', result:'pass',
        detail:'A Turing Machine can act identical to the LBA here. Passes at this level too.',
        rule:'✓ CSL ⊂ RE — passes, but tightest class = Type 1' }
    ]
  },
  {
    // Context-sensitive — aⁿbⁿcⁿdⁿ (4 symbols)
    patterns:['aⁿbⁿcⁿdⁿ','anbncndn','a^nb^nc^nd^n','a^n b^n c^n d^n','four equal counts','equal counts of four'],
    type:'cs',
    samples: ['ε', 'abcd', 'aabbccdd', 'aaabbbcccddd', 'aaaabbbbccccdddd'],

    steps:[
      { check:'Is it Regular (Type 3)?', result:'fail',
        detail:'Matching four equal quantities requires counting far beyond what a finite automaton can do. A DFA has no memory — it cannot even track n for one symbol, let alone four simultaneously.',
        rule:'✗ No DFA or regular expression can encode unbounded equal-count constraints',
        diagram:'dfa' },
      { check:'Is it Context-Free (Type 2)?', result:'fail',
        detail:'A PDA has only ONE stack. Even for aⁿbⁿcⁿ (three symbols) a stack is insufficient — for four symbols (aⁿbⁿcⁿdⁿ) the situation is strictly worse. The CFL Pumping Lemma is violated: any long string of the form aⁿbⁿcⁿdⁿ cannot be pumped while staying in the language.',
        rule:'✗ Single stack insufficient — CFL Pumping Lemma violated for 4 equal counts',
        diagram:'pda' },
      { check:'Is it Context-Sensitive (Type 1)?', result:'pass',
        detail:'A Linear Bounded Automaton handles aⁿbⁿcⁿdⁿ via repeated sweeps: each pass marks off one a, one b, one c, and one d (turning them into X, Y, Z, W). After n passes the tape is fully marked — the LBA accepts. The tape is bounded by the input length, which is exactly sufficient.',
        rule:'✓ LBA marks off one (a,b,c,d) quadruple per sweep — bounded tape suffices',
        diagram:'lba' },
      { check:'Is it Recursively Enumerable (Type 0)?', result:'pass',
        detail:'Every CS language is also RE — a TM trivially simulates the LBA. But membership is fully decidable (the LBA always halts), so Type 1 is the tightest and most precise classification.',
        rule:'✓ CSL ⊂ RE — passes everywhere, but tightest class = Type 1' }
    ]
  },
  {
    // Context-sensitive — aⁿbⁿcⁿdⁿeⁿ (5 symbols)
    patterns:['aⁿbⁿcⁿdⁿeⁿ','anbncndnen','a^nb^nc^nd^ne^n','a^n b^n c^n d^n e^n','five equal counts','equal counts of five'],
    type:'cs',
    samples: ['ε', 'abcde', 'aabbccddee', 'aaabbbcccdddeee'],

    steps:[
      { check:'Is it Regular (Type 3)?', result:'fail',
        detail:'Matching five independently equal quantities is far beyond any finite automaton. A DFA has no memory — it cannot count even one symbol, let alone track five equal groups simultaneously.',
        rule:'✗ No DFA or regular expression can encode five equal unbounded counts',
        diagram:'dfa' },
      { check:'Is it Context-Free (Type 2)?', result:'fail',
        detail:'A PDA with a single stack cannot verify five equal counts. Each additional symbol beyond two makes the problem strictly harder. The CFL Pumping Lemma is violated: pumping any section of aⁿbⁿcⁿdⁿeⁿ disrupts the five-way balance.',
        rule:'✗ Single stack grossly insufficient — 5 simultaneous counts require more power',
        diagram:'pda' },
      { check:'Is it Context-Sensitive (Type 1)?', result:'pass',
        detail:'A Linear Bounded Automaton solves aⁿbⁿcⁿdⁿeⁿ by making repeated left-to-right sweeps. Each pass marks off one a, one b, one c, one d, and one e (replacing them with markers X, Y, Z, W, V). After n complete sweeps the entire tape is marked — the LBA accepts. The tape is bounded by the input length 5n, which is linear and thus within LBA limits.',
        rule:'✓ LBA marks one (a,b,c,d,e) quintuple per sweep — bounded tape suffices',
        diagram:'lba' },
      { check:'Is it Recursively Enumerable (Type 0)?', result:'pass',
        detail:'Every CS language is also RE — a Turing Machine can simulate the LBA trivially. However, membership is fully decidable (the LBA always halts in O(n²) time), so Type 1 is the tightest and most accurate classification.',
        rule:'✓ CSL ⊂ RE — passes everywhere, but tightest class = Type 1' }
    ]
  },
  {
    // Recursively enumerable
    patterns:['halting problem','post correspondence problem','pcp','undecidable','semi-decidable','rices theorem','turing machine acceptance','any language reducible to tm acceptance','complement of recursive'],
    type:'re',
    samples: ['<M,w> where M halts on w', '<M1,0101>', '<M2,ε>', '<M3,111>', '<M_rev,abc>'],

    steps:[
      { check:'Is it Regular (Type 3)?', result:'fail',
        detail:'This requires unbounded computation with no pattern a finite automaton can track. A DFA with finite states cannot even approximate this.',
        rule:'✗ No finite automaton can decide this language',
        diagram:'dfa' },
      { check:'Is it Context-Free (Type 2)?', result:'fail',
        detail:'A single stack is hopelessly insufficient. This language\'s membership requires solving problems that no pushdown automaton can approach.',
        rule:'✗ No PDA or CFL grammar can generate this language',
        diagram:'pda' },
      { check:'Is it Context-Sensitive (Type 1)?', result:'fail',
        detail:'Even a tape bounded to input length is not enough. This language requires computation that may grow beyond any linear bound — an LBA cannot decide it.',
        rule:'✗ No Linear Bounded Automaton can decide this language',
        diagram:'lba' },
      { check:'Is it Recursively Enumerable (Type 0)?', result:'pass',
        detail:'A Turing Machine can ACCEPT strings in this language (though it may not halt on rejection — it could loop forever). This is the highest Chomsky class. The language is semi-decidable.',
        rule:'✓ TM accepts (but may not halt on rejection) — this is Type 0',
        diagram:'tm' }
    ]
  }
];

// ── Playground data ──────────────────────────────────────────────────────────
const PG_LANGS = {
  'reg|a*b*':      { level:3, name:'Type 3 — Regular',           color:'reg', label:'a*b*',
                    samples: ['ε', 'a', 'b', 'aa', 'ab', 'bb', 'aaa', 'aab', 'abb', 'bbb'] },
  'reg|ends-ab':   { level:3, name:'Type 3 — Regular',           color:'reg', label:'ends in ab',
                    samples: ['ab', 'aab', 'bab', 'aaab', 'abab', 'bbab', 'baaab', 'abbab'] },
  'cf|anbn':       { level:2, name:'Type 2 — Context-Free',      color:'cf',  label:'aⁿbⁿ',
                    samples: ['ε', 'ab', 'aabb', 'aaabbb', 'aaaabbbb', 'aaaaabbbbb'] },
  'cf|palindrome': { level:2, name:'Type 2 — Context-Free',      color:'cf',  label:'palindrome',
                    samples: ['ε', 'a', 'b', 'aa', 'bb', 'aba', 'bab', 'aaaa', 'abba', 'baab'] },
  'cs|anbncn':     { level:1, name:'Type 1 — Context-Sensitive', color:'cs',  label:'aⁿbⁿcⁿ',
                    samples: ['ε', 'abc', 'aabbcc', 'aaabbbccc', 'aaaabbbbcccc'] },
  'cs|ww':         { level:1, name:'Type 1 — Context-Sensitive', color:'cs',  label:'ww',
                    samples: ['ε', 'aa', 'bb', 'abab', 'baba', 'aabbaa', 'aaaa', 'bbbb', 'abbaabba'] },
  're|halting':    { level:0, name:'Type 0 — RE',                color:'re',  label:'Halting Problem',
                    samples: ['<M,w> where M halts on w', '<M1,0101>', '<M2,ε>', '<M3,111>', '<M_rev,abc>'] }
};

// Closure table: closed=true, not closed=false
const CLOSURE = {
  3:{ union:true,  intersection:true,  complement:true,  concatenation:true  },
  2:{ union:true,  intersection:false, complement:false, concatenation:true  },
  1:{ union:true,  intersection:true,  complement:true,  concatenation:true  },
  0:{ union:true,  intersection:true,  complement:false, concatenation:true  }
};

const CLOSURE_EXPLAIN = {
  3:{ union:'Regular languages are closed under union — build a product DFA or use NFA union construction.',
      intersection:'Regular languages are closed under intersection — product DFA construction works perfectly.',
      complement:'DFAs are trivially closed under complement — swap accepting and non-accepting states.',
      concatenation:'Regular languages are closed under concatenation — use NFA with ε-transitions.' },
  2:{ union:'CFLs are closed under union — add new start symbol S → S₁ | S₂.',
      intersection:'CFLs are NOT closed under intersection. Classic proof: {aⁿbⁿ} ∩ {bⁿcⁿ} = {aⁿbⁿcⁿ}, but aⁿbⁿcⁿ is not context-free!',
      complement:'CFLs are NOT closed under complement — this follows from non-closure under intersection (De Morgan\'s law).',
      concatenation:'CFLs are closed under concatenation — add production S → S₁S₂.' },
  1:{ union:'CSLs are closed under union.',
      intersection:'CSLs are closed under intersection.',
      complement:'CSLs are closed under complement — proven by the Immerman–Szelepcsényi theorem (1987–88), which shows that NSPACE(n) = co-NSPACE(n): any language is accepted by an NTM if and only if its complement is.',
      concatenation:'CSLs are closed under concatenation.' },
  0:{ union:'RE languages are closed under union.',
      intersection:'RE languages are closed under intersection.',
      complement:'RE languages are NOT closed under complement — complement of RE may not be RE (co-RE).',
      concatenation:'RE languages are closed under concatenation.' }
};

// Example output strings for playground result
const PG_OUTPUT_EXAMPLES = {
  '3|union':        { strings:['a', 'ab', 'aab', 'abb', 'aabb', 'bab'], desc:'strings from either regular language' },
  '3|intersection': { strings:['ε', 'a', 'aa', 'ab', 'aab', 'aabb'], desc:'strings matching both regular patterns' },
  '3|complement':   { strings:['ba', 'bba', 'aba', 'bab', 'abba'], desc:'strings NOT in the regular language (result is still regular)' },
  '3|concatenation':{ strings:['ab', 'aab', 'abb', 'aaab', 'abbb'], desc:'L1 followed by L2 (result is still regular)' },
  '2|union':        { strings:['ab', 'aabb', 'aaabbb', 'aa', 'abba', 'aabba'], desc:'strings from either CFL (result is still context-free)' },
  '2|intersection': { strings:['Cannot be determined in general'], desc:'CFL ∩ CFL is NOT guaranteed to be a CFL. Classic example: {aⁿbⁿ} ∩ {bⁿcⁿ} = {aⁿbⁿcⁿ} which is CS, not CF.' },
  '2|complement':   { strings:['Cannot be determined in general'], desc:'Complement of a CFL is NOT guaranteed to be a CFL (follows from non-closure under intersection by De Morgan\'s law).' },
  '2|concatenation':{ strings:['aabb', 'ababba', 'aabbab', 'abbaabb'], desc:'L1·L2 — concatenation of two CFLs is always a CFL.' },
  '1|union':        { strings:['aabbcc', 'aaabbbccc', 'abab', 'aabb'], desc:'strings from either CSL (result stays context-sensitive)' },
  '1|intersection': { strings:['aabbcc', 'aaabbbccc'], desc:'Intersection of two CSLs is always context-sensitive.' },
  '1|complement':   { strings:['strings not in L over Σ*'], desc:'Complement of a CSL is always context-sensitive (Immerman–Szelepcsényi theorem).' },
  '1|concatenation':{ strings:['aabbccaabbcc', 'longer CS strings'], desc:'Concatenation of two CSLs is always context-sensitive.' },
  '0|union':        { strings:['all strings from either RE language'], desc:'Union of two RE languages is always RE.' },
  '0|intersection': { strings:['strings in both RE languages'], desc:'Intersection of two RE languages is always RE.' },
  '0|complement':   { strings:['Language is co-RE — complement of an RE language'], desc:'Complement of an RE language is co-RE, which is NOT necessarily RE. (e.g., complement of Halting Problem is not RE).' },
  '0|concatenation':{ strings:['concatenated RE strings'], desc:'Concatenation of two RE languages is always RE.' }
};

// ── Compare property rows ────────────────────────────────────────────────────
const CMP_ROWS = [
  { section:'AUTOMATON & GRAMMAR' },
  { prop:'Automaton',        reg:'DFA / NFA',         cf:'Pushdown Automaton (PDA)', cs:'Linear Bounded Auto. (LBA)', re:'Turing Machine (TM)' },
  { prop:'Grammar Type',     reg:'Right-linear (Type 3)', cf:'Context-Free (Type 2)', cs:'Context-Sensitive (Type 1)', re:'Unrestricted (Type 0)' },
  { prop:'Memory',           reg:'None (finite states)',  cf:'Stack (LIFO)',            cs:'Tape bounded to O(n)',       re:'Tape unbounded' },
  { prop:'Deterministic?',   reg:'Yes (DFA ≡ NFA in power)',  cf:'No (DPDA ⊊ NPDA)',      cs:'Open question (DLBA = LBA?)', re:'No (NTM ≡ TM)' },

  { section:'DECIDABILITY' },
  // Membership: Regular/CFL/CSL are fully decidable. RE is semi-decidable (TM halts & accepts
  // if w ∈ L; may loop forever if w ∉ L). This is distinct from "undecidable".
  { prop:'Membership',       reg:'yes', cf:'yes', cs:'yes', re:'part' },
  // Emptiness: Regular & CFL are decidable. CSL emptiness is undecidable (reduces to halting problem).
  { prop:'Emptiness',        reg:'yes', cf:'yes', cs:'no',  re:'no'  },
  // Equivalence: Only Regular languages have a decidable equivalence problem.
  { prop:'Equivalence',      reg:'yes', cf:'no',  cs:'no',  re:'no'  },
  // Universality: Does L = Σ*? Decidable only for Regular.
  { prop:'Universality',     reg:'yes', cf:'no',  cs:'no',  re:'no'  },
  // Can a grammar of this type be ambiguous? (existence question — all four types can be)
  { prop:'Grammar Can Be Ambiguous?', reg:'yes', cf:'yes', cs:'yes', re:'yes' },
  // Is it algorithmically decidable whether a given grammar is ambiguous?
  // Undecidable for CFGs (proven via PCP reduction) and above. Fully decidable only for Regular.
  { prop:'Ambiguity Decidable?', reg:'yes', cf:'no', cs:'no', re:'no' },

  { section:'CLOSURE PROPERTIES' },
  // Union: all classes closed.
  { prop:'Union',            reg:'yes', cf:'yes', cs:'yes', re:'yes' },
  // Intersection: Regular & CS & RE closed. CFL NOT closed (e.g. {aⁿbⁿcⁿ} = {aⁿbⁿ} ∩ {bⁿcⁿ}).
  { prop:'Intersection',     reg:'yes', cf:'no',  cs:'yes', re:'yes' },
  // Intersection with Regular: CFL ∩ Regular = CFL (useful fact).
  { prop:'∩ with Regular',   reg:'yes', cf:'yes', cs:'yes', re:'yes' },
  // Complement: Regular ✓, CFL ✗, CSL ✓ (Immerman–Szelepcsényi theorem), RE ✗.
  { prop:'Complement',       reg:'yes', cf:'no',  cs:'yes', re:'no'  },
  // Concatenation: all classes closed.
  { prop:'Concatenation',    reg:'yes', cf:'yes', cs:'yes', re:'yes' },
  // Kleene Star: all classes closed.
  { prop:'Kleene Star',      reg:'yes', cf:'yes', cs:'yes', re:'yes' },
  // Reversal: all classes closed.
  { prop:'Reversal',         reg:'yes', cf:'yes', cs:'yes', re:'yes' },

  { section:'PUMPING LEMMA' },
  {
    prop:'Pumping Lemma',
    reg:'∃p: w=xyz, |xy|≤p, |y|≥1, xyⁱz∈L ∀i≥0',
    cf:'∃p: w=uvxyz, |vxy|≤p, |vy|≥1, uvⁱxyⁱz∈L ∀i≥0',
    cs:'No pumping lemma — use Myhill–Nerode or closure proofs',
    re:'No pumping lemma — undecidability arguments used instead'
  },

  { section:'COMPLEXITY' },
  // Time complexity of deciding membership:
  // Regular: O(n) with DFA. CFL: O(n³) via CYK (O(n²·|G|) with grammar).
  // CSL: PSPACE-complete (membership in NSPACE(n) ⊆ PSPACE). RE: semi-decidable only.
  { prop:'Membership complexity', reg:'O(n) — DFA simulation', cf:'O(n³) — CYK algorithm', cs:'PSPACE-complete', re:'Semi-decidable (may not halt)' },
  // Space complexity of deciding membership:
  { prop:'Space (membership)',    reg:'O(1) — constant states', cf:'O(n²) — CYK table',      cs:'O(n) — linear tape', re:'Unbounded' },

  { section:'EXAMPLES' },
  { prop:'Classic Example', reg:'(a|b)*abb  or  a*b*', cf:'aⁿbⁿ  (n≥1)',  cs:'aⁿbⁿcⁿ  (n≥1)',  re:'Halting Problem' },
  { prop:'Non-Example',     reg:'aⁿbⁿ (requires counting)', cf:'aⁿbⁿcⁿ (requires 2 stacks)', cs:'Halting Problem (undecidable)', re:'Co-RE languages (e.g. complement of Halting Problem)' },
  { prop:'Recognizing machine', reg:'Two-state DFA for a*b*', cf:'PDA with stack for aⁿbⁿ', cs:'LBA for aⁿbⁿcⁿ', re:'Universal TM' },
];